book-text-plasma-trap =  Não há como eles chegarem ao nosso esconderijo agora, certo?

book-text-holoparasite-info =  Obrigado por escolher nosso pacote holoparasitário! No cybersun, nos orgulhamos da tecnologia militar e industrial de ponta, e apreciamos muito sua contribuição para o nosso estabelecimento! Guardiões são seres úteis e inteligentes que se aninham dentro de seu corpo, completamente imunes a perigos comuns, como pressão, temperatura e até balas! Você comprou o pacote holoparasitário, que contém um ativador holoparasitário, um folheto de instruções, e nossa mercadoria softcap. Instruções de uso: 1. Ative o injetor holoparasitário (de preferência em uma área isolada). 2. Espere pelo formigamento e/ou sensação metafísica dolorosa. 3. Verifique seu holoparasite para a capacidade de comunicar e cooperar, e capacidade de entender suas ordens. 4. Use sua capacidade de lembrar-manifest para convocar ou recuperar o holoparasite de volta ao seu corpo. 5. Mantenha o holoparasite dentro de uma curta distância de si mesmo, caso contrário, ele será lembrado pela força! ATENÇÃO: Guardiões são seres metafísico, mas de sua saúde para existir.

book-text-ame-scribbles =  Não sei se já está treinado, por isso espero que isto ajude. O controlador AME precisa de energia LV e de um fio HV para sair. Verifique a área com um pé-de-cabra, se não tiver a certeza. Deve haver uma sala vazia ao lado onde encontrou isto, aquela sala está ligada para o EMA. Pode colocar um EMA em qualquer lugar se conseguir obter os fios para ele, no entanto. 3x3 grade de peças AME, multitool para desempacotá- los. Tenha cuidado para não 'armazenar' nada. O controlador AME adjacente horizontal ou vertical (não diagonal) a qualquer ponto. Com apenas 1 núcleo (que grade 3x3 irá levá- lo), não o aumente acima de 2. A regra dourada é 2 injeção para cada 1 núcleo. Você pode ir mais baixo para salvar combustível. O motor mais alto irá queimar e, eventualmente, fazê- lo explodir. Não se não se esqueça de reabastejar, tende a parar no pior momento possível.

book-text-agrichemkit-manual = Em seguida, a melhor opção é a de se fazer o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento com o tratamento

book-text-combat-bakery-kit =  Obrigado por escolher nosso kit de padaria de combate! Enclosed são dois (2) CyberSun patenteado lançando croissants, e um (1) patente pendente espada Baguette.
